site_name: Dvc Task

theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/logo.svg
  palette:
    primary: white
    accent: deep purple
  icon:
    repo: fontawesome/brands/github

repo_url: https://github.com/iterative/dvc-task
repo_name: iterative/dvc-task

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/iterative/

plugins:
- search
- gen-files:
    scripts:
    - docs/gen_ref_pages.py
- section-index
- mkdocstrings:
    handlers:
      python:
        rendering:
          show_submodules: no
    watch:
    - src/dvc_task
